name: London Night Photography
favicon: null
layout_spectrum: 0.6665989202447236
typography_spectrum: 0.8561560388188809
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.713405491085723
  lightness: 0.09029806475155056
  saturation: 0.9996547426562756
  rhythmicContrast: 0.6122255194932222
purpose: []
