name: London Night Photography
favicon: null
layout_spectrum: 0.84962
typography_spectrum: 0.99796
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#251e14'
    - '#f7f7f7'
    - '#5b8e78'
    - '#e0014d'
    - '#b57514'
  brandStrength: 0.713405491085723
  lightness: 0.09029806475155056
  saturation: 0.9996547426562756
  rhythmicContrast: 0.6122255194932222
purpose: []
